ALTER TABLE pet_aura ADD column basepoints3 int(11) NOT NULL DEFAULT '0' AFTER basepoints2;
ALTER TABLE pet_aura ADD column basepoints4 int(11) NOT NULL DEFAULT '0' AFTER basepoints3;
ALTER TABLE pet_aura ADD column basepoints5 int(11) NOT NULL DEFAULT '0' AFTER basepoints4;
ALTER TABLE pet_aura ADD column basepoints6 int(11) NOT NULL DEFAULT '0' AFTER basepoints5;
ALTER TABLE pet_aura ADD column basepoints7 int(11) NOT NULL DEFAULT '0' AFTER basepoints6;
ALTER TABLE pet_aura ADD column basepoints8 int(11) NOT NULL DEFAULT '0' AFTER basepoints7;
ALTER TABLE pet_aura ADD column basepoints9 int(11) NOT NULL DEFAULT '0' AFTER basepoints8;
ALTER TABLE pet_aura ADD column basepoints10 int(11) NOT NULL DEFAULT '0' AFTER basepoints9;
ALTER TABLE pet_aura ADD column basepoints11 int(11) NOT NULL DEFAULT '0' AFTER basepoints10;
ALTER TABLE pet_aura ADD column basepoints12 int(11) NOT NULL DEFAULT '0' AFTER basepoints11;
ALTER TABLE pet_aura ADD column basepoints13 int(11) NOT NULL DEFAULT '0' AFTER basepoints12;
ALTER TABLE pet_aura ADD column basepoints14 int(11) NOT NULL DEFAULT '0' AFTER basepoints13;
ALTER TABLE pet_aura ADD column basepoints15 int(11) NOT NULL DEFAULT '0' AFTER basepoints14;
ALTER TABLE pet_aura ADD column basepoints16 int(11) NOT NULL DEFAULT '0' AFTER basepoints15;
ALTER TABLE pet_aura ADD column basepoints17 int(11) NOT NULL DEFAULT '0' AFTER basepoints16;
ALTER TABLE pet_aura ADD column basepoints18 int(11) NOT NULL DEFAULT '0' AFTER basepoints17;
ALTER TABLE pet_aura ADD column basepoints19 int(11) NOT NULL DEFAULT '0' AFTER basepoints18;
ALTER TABLE pet_aura ADD column basepoints20 int(11) NOT NULL DEFAULT '0' AFTER basepoints19;

ALTER TABLE pet_aura ADD column periodictime3 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime2;
ALTER TABLE pet_aura ADD column periodictime4 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime3;
ALTER TABLE pet_aura ADD column periodictime5 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime4;
ALTER TABLE pet_aura ADD column periodictime6 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime5;
ALTER TABLE pet_aura ADD column periodictime7 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime6;
ALTER TABLE pet_aura ADD column periodictime8 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime7;
ALTER TABLE pet_aura ADD column periodictime9 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime8;
ALTER TABLE pet_aura ADD column periodictime10 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime9;
ALTER TABLE pet_aura ADD column periodictime11 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime10;
ALTER TABLE pet_aura ADD column periodictime12 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime11;
ALTER TABLE pet_aura ADD column periodictime13 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime12;
ALTER TABLE pet_aura ADD column periodictime14 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime13;
ALTER TABLE pet_aura ADD column periodictime15 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime14;
ALTER TABLE pet_aura ADD column periodictime16 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime15;
ALTER TABLE pet_aura ADD column periodictime17 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime16;
ALTER TABLE pet_aura ADD column periodictime18 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime17;
ALTER TABLE pet_aura ADD column periodictime19 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime18;
ALTER TABLE pet_aura ADD column periodictime20 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime19;

ALTER TABLE character_aura ADD column basepoints3 int(11) NOT NULL DEFAULT '0' AFTER basepoints2;
ALTER TABLE character_aura ADD column basepoints4 int(11) NOT NULL DEFAULT '0' AFTER basepoints3;
ALTER TABLE character_aura ADD column basepoints5 int(11) NOT NULL DEFAULT '0' AFTER basepoints4;
ALTER TABLE character_aura ADD column basepoints6 int(11) NOT NULL DEFAULT '0' AFTER basepoints5;
ALTER TABLE character_aura ADD column basepoints7 int(11) NOT NULL DEFAULT '0' AFTER basepoints6;
ALTER TABLE character_aura ADD column basepoints8 int(11) NOT NULL DEFAULT '0' AFTER basepoints7;
ALTER TABLE character_aura ADD column basepoints9 int(11) NOT NULL DEFAULT '0' AFTER basepoints8;
ALTER TABLE character_aura ADD column basepoints10 int(11) NOT NULL DEFAULT '0' AFTER basepoints9;
ALTER TABLE character_aura ADD column basepoints11 int(11) NOT NULL DEFAULT '0' AFTER basepoints10;
ALTER TABLE character_aura ADD column basepoints12 int(11) NOT NULL DEFAULT '0' AFTER basepoints11;
ALTER TABLE character_aura ADD column basepoints13 int(11) NOT NULL DEFAULT '0' AFTER basepoints12;
ALTER TABLE character_aura ADD column basepoints14 int(11) NOT NULL DEFAULT '0' AFTER basepoints13;
ALTER TABLE character_aura ADD column basepoints15 int(11) NOT NULL DEFAULT '0' AFTER basepoints14;
ALTER TABLE character_aura ADD column basepoints16 int(11) NOT NULL DEFAULT '0' AFTER basepoints15;
ALTER TABLE character_aura ADD column basepoints17 int(11) NOT NULL DEFAULT '0' AFTER basepoints16;
ALTER TABLE character_aura ADD column basepoints18 int(11) NOT NULL DEFAULT '0' AFTER basepoints17;
ALTER TABLE character_aura ADD column basepoints19 int(11) NOT NULL DEFAULT '0' AFTER basepoints18;
ALTER TABLE character_aura ADD column basepoints20 int(11) NOT NULL DEFAULT '0' AFTER basepoints19;

ALTER TABLE character_aura ADD column periodictime3 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime2;
ALTER TABLE character_aura ADD column periodictime4 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime3;
ALTER TABLE character_aura ADD column periodictime5 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime4;
ALTER TABLE character_aura ADD column periodictime6 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime5;
ALTER TABLE character_aura ADD column periodictime7 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime6;
ALTER TABLE character_aura ADD column periodictime8 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime7;
ALTER TABLE character_aura ADD column periodictime9 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime8;
ALTER TABLE character_aura ADD column periodictime10 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime9;
ALTER TABLE character_aura ADD column periodictime11 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime10;
ALTER TABLE character_aura ADD column periodictime12 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime11;
ALTER TABLE character_aura ADD column periodictime13 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime12;
ALTER TABLE character_aura ADD column periodictime14 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime13;
ALTER TABLE character_aura ADD column periodictime15 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime14;
ALTER TABLE character_aura ADD column periodictime16 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime15;
ALTER TABLE character_aura ADD column periodictime17 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime16;
ALTER TABLE character_aura ADD column periodictime18 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime17;
ALTER TABLE character_aura ADD column periodictime19 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime18;
ALTER TABLE character_aura ADD column periodictime20 int(11) unsigned NOT NULL DEFAULT '0' AFTER periodictime19;
